#! /usr/bin/env bash

if which snakemake &>/dev/null; then
  foo=1
else
  echo -e "ERROR:\nSnakemake installation is required to run LepWrap, but not found in the current environment."
  exit 1
fi

if [[ -z "$1" ]]; then
  echo "Perform the modules of Lep-Map3. Make sure config.yaml is properly configured for how you intend to run things."
  echo ""
  echo "[usage] LepMWrap <number of threads to use>"
  echo "[example] LepWrap 16" 
  exit 1
fi

snakemake --cores $1 --snakefile ./rules/Snakefile --directory .
