#! /usr/bin/env bash

if [[ -z "$1" ]]; then
cat <<EOF

Convert Lep-Map3 interval files into a single Lep-Anchor input file.

[usage]:	lepmap2anchor <marker_file>
[example]: 	lepmap2anchor snps.txt

EOF
  exit 1
fi

LG=$(ls 7_Intervals/*.intervals | wc -l)

if [ ! -f $1 ]; then
    echo "Error: marker file $(echo $1) not found. It may be generated using extract_markers.sh"
    exit 1
fi

echo "Identified $LG interval files in 7_Intervals/ directory"

for i in $(seq 1 $LG); do
    awk -vn=$i '(NR==FNR){map[NR-1]=$0}(NR!=FNR){$1=map[$1] "\t" n;print}' $1 7_Intervals/ordered.$i.intervals
done > lepmap3_intervals.la


echo "Created Lep-Anchor input file lepmap3_intervals.la"
